package com.example.tesla

sealed class Routes(val route: String){
    object splashscreen: Routes("splashscreen")
    object Login: Routes("login")
    object SignUp: Routes("signup")
    object ForgotPassword: Routes("forgotpassword")
    object Rules: Routes("rules")
    object level1: Routes("level1")
    object level2: Routes("level2")
    object level3: Routes("level3")
    object level4: Routes("level4")
    object level5: Routes("level5")
    object level6: Routes("level6")
    object level7: Routes("level7")
    object level8: Routes("level8")
    object level9: Routes("level9")
    object level10: Routes("level10")
    object level11: Routes("level11")
    object level12: Routes("level12")
    object level13: Routes("level13")
    object level14: Routes("level14")
    object level15: Routes("level15")
    object level16: Routes("level16")
    object level17: Routes("level17")
    object level18: Routes("level18")
    object level19: Routes("level19")
    object level20: Routes("level20")
    object congrats: Routes("congrats")
    object status: Routes("status")
    object rulesdrawer: Routes("rulesdrawer")
    object tesla: Routes("tesla")
    object eel: Routes("eel")
    object developer: Routes("developer")
}
